CREATE TABLE user_t (
    USERID VARCHAR2(20)PRIMARY KEY,
    USERNAME VARCHAR2(20) NOT NULL,
    PASSWORD VARCHAR2(20) NOT NULL,
    GENDER CHAR(1) CHECK(GENDER IN ('m', 'f')),
    EMAIL VARCHAR2(30),
    PHONE VARCHAR2(20),
    ADDRESS VARCHAR2(40) NOT NULL,
    REGISTERDATE DATE DEFAULT SYSDATE  
);

CREATE TABLE product_t (
    PID VARCHAR2(30) PRIMARY KEY,
    CATEGORY VARCHAR2(20) NOT NULL,
    PRODUCTNAME VARCHAR2(50) NOT NULL,
    EXPLANATION VARCHAR2(2048),
    PRICE NUMBER(30) NOT NULL,
    REGISTERDATE DATE DEFAULT SYSDATE,
    INVENTORY NUMBER(20) NOT NULL,
    ISBASKET CHAR(1) CHECK(ISBASKET IN ('y', 'n'))
);

CREATE TABLE order_t (
    TID VARCHAR2(40) PRIMARY KEY,
    OID VARCHAR2(40) NOT NULL,
    PID VARCHAR2(30) NOT NULL,
    PRODUCTNAME VARCHAR2(50) NOT NULL,
    QTY NUMBER(20) NOT NULL,
    TOTALPRICE NUMBER(30) NOT NULL,
    USERID VARCHAR2(20) NOT NULL,
    ADDRESS VARCHAR2(40) NOT NULL,
    PHONE VARCHAR2(20),
    ORDERSTAT VARCHAR2(20) NOT NULL,
    ORDERDATE DATE DEFAULT SYSDATE,
    ORDERMEMO VARCHAR2(1024),
    PAYMENTMETHOD VARCHAR2(20) NOT NULL,
    FOREIGN KEY(PID) REFERENCES product_t(PID),
    FOREIGN KEY(USERID) REFERENCES user_t(USERID)
);

-- 아직 생성 안함 
CREATE TABLE order_detail (
    TID VARCHAR2(40) NOT NULL,
    OID VARCHAR2(40) NOT NULL,
    PRODUCTNAME VARCHAR2(50) NOT NULL,
    QTY NUMBER(20) NOT NULL,
    PRICE NUMBER(30) NOT NULL,
    FOREIGN KEY(TID) REFERENCES order_t(TID)
);